name: Terraform Plan

on:
  workflow_dispatch:

permissions:
  contents: read

env:
  TF_ROOT: terraform
  PLAN_BUCKET: kanazir-tf-plan

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.14.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Detect ENV based on branch
        run: |
          if [ "${{ github.ref_name }}" == "dev" ]; then ENVIRONMENT="dev";
          elif [ "${{ github.ref_name }}" == "stage" ]; then ENVIRONMENT="stage";
          elif [ "${{ github.ref_name }}" == "prod" ]; then ENVIRONMENT="prod";
          else echo "Unsupported branch"; exit 1; fi

          echo "ENVIRONMENT=$ENVIRONMENT" >> $GITHUB_ENV
          echo "TF_VAR_FILE=env-config/$ENVIRONMENT.tfvars" >> $GITHUB_ENV
          echo "STACK_DIR=terraform/stacks/$ENVIRONMENT" >> $GITHUB_ENV

      - name: Terraform Init
        working-directory: ${{ env.STACK_DIR }}
        run: |
          terraform init \
            -backend-config="../../env-config/${ENVIRONMENT}.backend"

      - name: Terraform Validate
        working-directory: ${{ env.STACK_DIR }}
        run: |
          terraform validate

      - name: Terraform Plan
        id: plan
        working-directory: ${{ env.STACK_DIR }}
        run: |
          terraform plan \
              -var-file="../../env-config/${ENVIRONMENT}.tfvars" \
              -out=plan-${ENVIRONMENT}.tfplan \
              -no-color

      - name: Upload plan to S3 bucket
        run: |
          aws s3 cp "${{ env.STACK_DIR }}/plan-${ENVIRONMENT}.tfplan" \
            s3://${{ env.PLAN_BUCKET }}/${ENVIRONMENT}/plan-${ENVIRONMENT}.tfplan
